import { z } from 'zod';
export declare const createEventSchema: z.ZodObject<{
    body: z.ZodObject<{
        name: z.ZodString;
        description: z.ZodString;
        location: z.ZodString;
        category: z.ZodString;
        guestAllowed: z.ZodDefault<z.ZodBoolean>;
        ticketLimit: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
        remainingTickets: z.ZodNumber;
        cancellationDeadline: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
        latitude: z.ZodOptional<z.ZodNumber>;
        longitude: z.ZodOptional<z.ZodNumber>;
        checkinRadiusMeters: z.ZodOptional<z.ZodNumber>;
        eventStartTime: z.ZodCoercedDate<unknown>;
        eventEndTime: z.ZodCoercedDate<unknown>;
        registrationStart: z.ZodCoercedDate<unknown>;
        registrationEnd: z.ZodCoercedDate<unknown>;
        faqs: z.ZodOptional<z.ZodArray<z.ZodObject<{
            question: z.ZodString;
            answer: z.ZodString;
        }, z.core.$strip>>>;
        status: z.ZodNumber;
        isDraft: z.ZodDefault<z.ZodBoolean>;
        createdAt: z.ZodCoercedDate<unknown>;
        updatedAt: z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const updateEventSchema: z.ZodObject<{
    body: z.ZodObject<{
        name: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        location: z.ZodOptional<z.ZodString>;
        category: z.ZodOptional<z.ZodString>;
        guestAllowed: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        ticketLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
        remainingTickets: z.ZodOptional<z.ZodNumber>;
        cancellationDeadline: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>>;
        latitude: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
        longitude: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
        checkinRadiusMeters: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
        eventStartTime: z.ZodOptional<z.ZodCoercedDate<unknown>>;
        eventEndTime: z.ZodOptional<z.ZodCoercedDate<unknown>>;
        registrationStart: z.ZodOptional<z.ZodCoercedDate<unknown>>;
        registrationEnd: z.ZodOptional<z.ZodCoercedDate<unknown>>;
        faqs: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodObject<{
            question: z.ZodString;
            answer: z.ZodString;
        }, z.core.$strip>>>>;
        status: z.ZodOptional<z.ZodNumber>;
        isDraft: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
        createdAt: z.ZodOptional<z.ZodCoercedDate<unknown>>;
        updatedAt: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const batchUpdateSchema: z.ZodObject<{
    body: z.ZodObject<{
        updates: z.ZodArray<z.ZodIntersection<z.ZodObject<{
            eventId: z.ZodString;
        }, z.core.$strip>, z.ZodObject<{
            name: z.ZodOptional<z.ZodString>;
            description: z.ZodOptional<z.ZodString>;
            location: z.ZodOptional<z.ZodString>;
            category: z.ZodOptional<z.ZodString>;
            guestAllowed: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
            ticketLimit: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodNumber>>>;
            remainingTickets: z.ZodOptional<z.ZodNumber>;
            cancellationDeadline: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>>;
            latitude: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
            longitude: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
            checkinRadiusMeters: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
            eventStartTime: z.ZodOptional<z.ZodCoercedDate<unknown>>;
            eventEndTime: z.ZodOptional<z.ZodCoercedDate<unknown>>;
            registrationStart: z.ZodOptional<z.ZodCoercedDate<unknown>>;
            registrationEnd: z.ZodOptional<z.ZodCoercedDate<unknown>>;
            faqs: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodObject<{
                question: z.ZodString;
                answer: z.ZodString;
            }, z.core.$strip>>>>;
            status: z.ZodOptional<z.ZodNumber>;
            isDraft: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
            createdAt: z.ZodOptional<z.ZodCoercedDate<unknown>>;
            updatedAt: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodCoercedDate<unknown>>>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
}, z.core.$strip>;
//# sourceMappingURL=event.schema.d.ts.map