services:
  account-db:
    image: postgres:15-alpine
    container_name: account_postgres_local
    environment:
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      POSTGRES_DB: ${ACCOUNT_DB_NAME}
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
