sonar.projectKey=event-ticketing-system-api
sonar.projectName=event-ticketing-system-api
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.sources=backend
sonar.tests=backend/account/tests,backend/event/tests,backend/transaction/tests,backend/ticket/tests

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.pytest_cache/**,**/tests/**,docs/**,scripts/**
sonar.test.inclusions=backend/**/tests/**/*.py

# Enable after generating coverage.xml from pytest-cov.
# sonar.python.coverage.reportPaths=coverage.xml
