apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-sql-proxy-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: cloud-sql-sa@ticketing-system-498218.iam.gserviceaccount.com
