apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      serviceAccountName: cloud-sql-proxy-sa
      containers:
        - name: event-api
          image: asia-east1-docker.pkg.dev/ticketing-system-498218/cloud-run-source-deploy/event-ticketing-system-api/event-api:336aa67
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SERVICE
              value: "event"
            - name: ENV
              value: "gke"
            - name: EVENT_DB_HOST
              value: "127.0.0.1"
            - name: EVENT_DB_PORT
              value: "5432"
            - name: EVENT_DB_USER
              value: "postgres"
            - name: EVENT_DB_NAME
              value: "event_db"
            - name: EVENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: event-db-password
            - name: TICKET_SERVICE_URL
              value: "http://ticket-service"
            - name: TRANSACTION_SERVICE_URL
              value: "http://transaction-service"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jwt-secret-key
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: internal-api-key
        - name: cloud-sql-proxy-event
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
          args:
            - "--structured-logs"
            - "--address=0.0.0.0"
            - "--port=5432"
            - "ticketing-system-498218:asia-east1:event-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: default
spec:
  selector:
    app: event-service
  ports:
    - port: 80
      targetPort: 8080
